version: '3'

services:
    db:
        container_name: nextcloud_db
        image: postgres:latest
        environment: 
            POSTGRES_USER: nextcloud
            POSTGRES_PASSWORD: nextcloud
            POSTGRES_DB: nextcloud
        volumes:
            - nextcloud_db:/var/lib/postgresql/data
        restart: always

    nextcloud:
        container_name: nextcloud
        image: nextcloud:latest
        volumes: 
            - nextcloud_data:/var/www/html
        expose:
            - 8080
        ports:
            - 8080:80
        restart: always

volumes:
    nextcloud_db:
        external: true
    nextcloud_data:
        external: true